### ISSUE TITLE
SCM polling failed, could not lock config file .git/config

### ISSUE THREAD

**Issue by thirota** [thirota/git-client-plugin#2]
- CentOS 6.4 x86_64
- Jenkins 1.544
- git 1.8.5.2
- Atlassian Stash v2.10
- git-client-plugin 7e914a157ee6ed595317ad974061480869852adc

```
Started on 2013/12/25 9:34:52
Using strategy: Default
[poll] Last Built Revision: Revision 48cbcad0f987744f58895a41bc2ad4052da36d35 (origin/master)
using .gitcredentials to set credentials
Could not remove the credential section from the git configuration
FATAL: hudson.plugins.git.GitException: Command "git config --local credential.helper store --file="/tmp/git5660285639643862372.credentials"" returned status code 255:
stdout: 
stderr: error: could not lock config file .git/config: ??????????????????????

hudson.util.IOException2: hudson.plugins.git.GitException: Command "git config --local credential.helper store --file="/tmp/git5660285639643862372.credentials"" returned status code 255:
stdout: 
stderr: error: could not lock config file .git/config: ??????????????????????

    at hudson.plugins.git.GitSCM.compareRemoteRevisionWith(GitSCM.java:458)
    at hudson.scm.SCM._compareRemoteRevisionWith(SCM.java:356)
    at hudson.scm.SCM.poll(SCM.java:373)
    at hudson.model.AbstractProject._poll(AbstractProject.java:1584)
    at hudson.model.AbstractProject.poll(AbstractProject.java:1493)
    at hudson.triggers.SCMTrigger$Runner.runPolling(SCMTrigger.java:456)
    at hudson.triggers.SCMTrigger$Runner.run(SCMTrigger.java:485)
    at hudson.util.SequentialExecutionQueue$QueueEntry.run(SequentialExecutionQueue.java:118)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: hudson.plugins.git.GitException: Command "git config --local credential.helper store --file="/tmp/git5660285639643862372.credentials"" returned status code 255:
stdout: 
stderr: error: could not lock config file .git/config: ??????????????????????

    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1103)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1080)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:931)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:981)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:939)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.getHeadRev(CliGitAPIImpl.java:1451)
    at hudson.plugins.git.GitSCM.compareRemoteRevisionWithImpl(GitSCM.java:488)
    at hudson.plugins.git.GitSCM.compareRemoteRevisionWith(GitSCM.java:456)
    ... 12 more
Done. Took 1 秒
No changes
```

**Comment by thirota** [comment]
timeout
